[project]
name = "goes-virtualizarr"
requires-python = ">3.10"

dependencies = [
  "virtualizarr@git+https://github.com/zarr-developers/VirtualiZarr",
  "xarray",
  "ipython",
  "fastparquet"
]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.dependencies]
h5py = "*"
